version: '3.7'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/home/taciomcosta/Documents/docker-recipes/prometheus-config.yml
      #- ./alert.rules:/etc/prometheus/alert.rules
    ports:
      - 9090:9090
    #networks:
      #- "monitoring-network"
  #grafana:
    #image: grafana/grafana
    #container_name: grafana
    #volumes:
      #- ./data/grafana/data:/var/lib/grafana
    #ports:
      #- 3000:3000
    #networks:
      #- "monitoring-network"
    #depends_on:
      #- prometheus
  #alertmanager:
    #image: prom/alertmanager
    #container_name: alertmanager
    #volumes:
      #- ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    #ports:
      #- 9093:9093
    #networks:
      #- "monitoring-network"
      #
#networks:
  #monitoring-network:
    #driver: bridge
