version: '3.1'

services:
  postgres:
    image: postgres:12.1-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
        - pgdata:/home/taciomcosta/data/postgres
    ports:
        - 5432:5432

volumes:
    pgdata:
        driver: local
