version: "3.8"
services:
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - "discovery.type=single-node"
            - "xpack.security.enabled=false"
        networks:
          - elastic
        volumes:
          - elasticsearch-data:/home/taciomcosta/data
        #ulimits:
          #memlock:
            #soft: -1
            #hard: -1
        #ulimits:
            #memlock:
                #soft: -1
                #hard: -1
        deploy:
            resources:
                limits:
                    #cpus: "1"
                    memory: 3000M
    kibana:
        image: docker.elastic.co/kibana/kibana:7.12.0
        container_name: kibana
        ports:
          - 5601:5601
        environment:
          ELASTICSEARCH_URL: http://elastic:9200
          ELASTICSEARCH_HOSTS: '["http://elastic:9200"]'
        networks:
          - elastic
networks:
  elastic:
    driver: bridge
volumes:
  elasticsearch-data:
    driver: local
